const express = require('express');
const router = express.Router();
const userController = require('../controllers/users_controller');
router.get('/profile',userController.profile);
router.get('/sign-up',userController.signUp);
router.get('/sign-in',userController.signIn);
router.post('/create',userController.create);
router.post('/createsession',userController.createsession);
console.log(`Route is loading`);
module.exports = router;